export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English (US)', nativeName: 'English (US)', flag: '🇺🇸' },
  { code: 'en-gb', name: 'English (UK)', nativeName: 'English (UK)', flag: '🇬🇧' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
];

export const DEFAULT_LANGUAGE: LanguageOption = SUPPORTED_LANGUAGES[0];

const STORAGE_KEY = 'os_graph_lang';

export function getSavedLanguage(): LanguageOption {
  if (typeof window !== 'undefined') {
    try {
      const params = new URLSearchParams(window.location.search);
      const urlLang = params.get('lang');
      if (urlLang) {
        const match = SUPPORTED_LANGUAGES.find((lang) => lang.code === urlLang);
        if (match) return match;
      }
    } catch {
      return DEFAULT_LANGUAGE;
    }
  }
  if (typeof localStorage === 'undefined') return DEFAULT_LANGUAGE;
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (!saved) return DEFAULT_LANGUAGE;
    const match = SUPPORTED_LANGUAGES.find((lang) => lang.code === saved);
    return match || DEFAULT_LANGUAGE;
  } catch {
    return DEFAULT_LANGUAGE;
  }
}

export function saveLanguage(code: string): void {
  if (typeof localStorage === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY, code);
  } catch {
    return;
  }
}

export type TranslationKey =
  | 'filters'
  | 'searchPlaceholder'
  | 'all'
  | 'overview'
  | 'systems'
  | 'compare'
  | 'kernel'
  | 'inception'
  | 'developer'
  | 'license'
  | 'primaryAuthor'
  | 'distributionTerms'
  | 'targetArchitectures'
  | 'lineageRelationships'
  | 'upstreamArchitecture'
  | 'downstreamDerivatives'
  | 'rootArchitecture'
  | 'terminalDistribution'
  | 'wikipediaDossier'
  | 'photoAlbum'
  | 'syncing'
  | 'loadingMaterials'
  | 'viewWikipedia'
  | 'expandImage'
  | 'unavailableIn'
  | 'showingEnglish'
  | 'close'
  | 'zoomIn'
  | 'zoomOut'
  | 'resetZoom'
  | 'graphFilters'
  | 'significanceThreshold'
  | 'majorTier'
  | 'notableTier'
  | 'allTier'
  | 'islandsSectors'
  | 'reset'
  | 'timeline'
  | 'systemComparison'
  | 'comparatorSubtitle'
  | 'closeComparator'
  | 'searchComparePlaceholder'
  | 'quickComparisons'
  | 'concurrentGen'
  | 'bothOriginatedIn'
  | 'predates'
  | 'by'
  | 'years'
  | 'year'
  | 'swapSystems'
  | 'locateInGraph'
  | 'phylogeneticKinship'
  | 'separation'
  | 'steps'
  | 'isDirectAncestorOf'
  | 'generationsDownLineage'
  | 'lowestCommonAncestor'
  | 'bothTraceLca'
  | 'traceToLca'
  | 'independentLineages'
  | 'architecturalSpecMatrix'
  | 'metric'
  | 'kernelModel'
  | 'phylogeneticFamily'
  | 'licenseModel'
  | 'wikipediaSitelinks'
  | 'links'
  | 'targetCpuOverlap'
  | 'overlap'
  | 'shared'
  | 'sharedByBoth'
  | 'only';

const enDict: Record<TranslationKey, string> = {
  filters: 'Filters',
  searchPlaceholder: 'Search...',
  all: 'All',
  overview: 'Overview',
  systems: 'Systems',
  compare: 'Compare',
  kernel: 'Kernel',
  inception: 'Inception',
  developer: 'Developer',
  license: 'License',
  primaryAuthor: 'Primary Author',
  distributionTerms: 'Distribution Terms',
  targetArchitectures: 'Target Architectures',
  lineageRelationships: 'Lineage Relationships',
  upstreamArchitecture: 'Upstream Architecture',
  downstreamDerivatives: 'Downstream Derivatives',
  rootArchitecture: 'Independent Genesis / Root Architecture',
  terminalDistribution: 'Terminal Distribution (No Derivatives)',
  wikipediaDossier: 'Wikipedia Dossier',
  photoAlbum: 'Materials & Media',
  syncing: 'Syncing',
  loadingMaterials: 'Loading materials & media...',
  viewWikipedia: 'View Wikipedia Dossier',
  expandImage: 'Expand Image',
  unavailableIn: 'Unavailable in',
  showingEnglish: 'showing English',
  close: 'Close',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  resetZoom: 'Reset zoom',
  graphFilters: 'Graph Filters',
  significanceThreshold: 'Significance Threshold',
  majorTier: 'Major (10+)',
  notableTier: 'Notable (5+)',
  allTier: 'All (0+)',
  islandsSectors: 'Islands & Sectors',
  reset: 'Reset',
  timeline: 'Timeline',
  systemComparison: 'System Comparison',
  comparatorSubtitle: 'Cross-system architectural analysis & phylogenetic lineage',
  closeComparator: 'Close comparator',
  searchComparePlaceholder: 'Search an operating system to compare against...',
  quickComparisons: 'Quick Comparisons:',
  concurrentGen: 'Concurrent Generation',
  bothOriginatedIn: 'Both systems originated in',
  predates: 'predates',
  by: 'by',
  years: 'years',
  year: 'year',
  swapSystems: 'Swap primary and comparative systems',
  locateInGraph: 'Locate in Graph',
  phylogeneticKinship: 'Phylogenetic Kinship & Convergence Path',
  separation: 'Separation',
  steps: 'steps',
  isDirectAncestorOf: 'is a direct ancestor of',
  generationsDownLineage: 'generation(s) down the lineage',
  lowestCommonAncestor: 'Lowest Common Ancestor (LCA)',
  bothTraceLca: 'Both systems trace their root phylogenetic heritage back to this milestone.',
  traceToLca: 'Trace to LCA',
  independentLineages: 'Independent Lineages. No direct shared phylogenetic ancestor recorded in the system graph.',
  architecturalSpecMatrix: 'Architectural Spec Matrix',
  metric: 'Metric',
  kernelModel: 'Kernel Model',
  phylogeneticFamily: 'Phylogenetic Family',
  licenseModel: 'License Model',
  wikipediaSitelinks: 'Wikipedia Sitelinks',
  links: 'links',
  targetCpuOverlap: 'Target CPU Architecture Overlap',
  overlap: 'Overlap',
  shared: 'Shared',
  sharedByBoth: 'Shared by Both',
  only: 'Only',
};

const enGbDict: Record<TranslationKey, string> = {
  ...enDict,
  license: 'Licence',
  licenseModel: 'Licence Model',
};

export const TRANSLATIONS: Record<string, Record<TranslationKey, string>> = {
  en: enDict,
  'en-gb': enGbDict,
  ru: {
    filters: 'Фильтры',
    searchPlaceholder: 'Поиск...',
    all: 'Все',
    overview: 'Обзор',
    systems: 'Систем',
    compare: 'Сравнить',
    kernel: 'Ядро',
    inception: 'Создание',
    developer: 'Разработчик',
    license: 'Лицензия',
    primaryAuthor: 'Основной автор',
    distributionTerms: 'Условия распространения',
    targetArchitectures: 'Архитектуры CPU',
    lineageRelationships: 'Эволюционные связи',
    upstreamArchitecture: 'Предки и основа',
    downstreamDerivatives: 'Прямые потомки',
    rootArchitecture: 'Корневая архитектура',
    terminalDistribution: 'Конечная ветка (без потомков)',
    wikipediaDossier: 'Материалы Википедии',
    photoAlbum: 'Материалы и медиа',
    syncing: 'Синхронизация',
    loadingMaterials: 'Загрузка материалов и медиа...',
    viewWikipedia: 'Открыть статью Википедии',
    expandImage: 'Увеличить изображение',
    unavailableIn: 'Недоступно на',
    showingEnglish: 'показана версия на английском',
    close: 'Закрыть',
    zoomIn: 'Приблизить',
    zoomOut: 'Отдалить',
    resetZoom: 'Сбросить масштаб',
    graphFilters: 'Фильтры графа',
    significanceThreshold: 'Порог значимости',
    majorTier: 'Ключевые (10+)',
    notableTier: 'Заметные (5+)',
    allTier: 'Все (0+)',
    islandsSectors: 'Секторы и семейства',
    reset: 'Сброс',
    timeline: 'Хронология',
    systemComparison: 'Сравнение систем',
    comparatorSubtitle: 'Кросс-системный архитектурный анализ и филогенетическая родословная',
    closeComparator: 'Закрыть сравнение',
    searchComparePlaceholder: 'Поиск ОС для сравнения...',
    quickComparisons: 'Быстрое сравнение:',
    concurrentGen: 'Одно поколение',
    bothOriginatedIn: 'Обе системы появились в',
    predates: 'предшествует',
    by: 'на',
    years: 'лет',
    year: 'год',
    swapSystems: 'Поменять системы местами',
    locateInGraph: 'Показать на графе',
    phylogeneticKinship: 'Филогенетическое родство и путь схождения',
    separation: 'Дистанция',
    steps: 'шагов',
    isDirectAncestorOf: 'является прямым предком',
    generationsDownLineage: 'поколений по родословной',
    lowestCommonAncestor: 'Ближайший общий предок (LCA)',
    bothTraceLca: 'Обе системы ведут свое филогенетическое наследие от этого ключевого узла.',
    traceToLca: 'Путь к LCA',
    independentLineages: 'Независимые ветви. Прямых общих предков в графе не зафиксировано.',
    architecturalSpecMatrix: 'Матрица архитектурных спецификаций',
    metric: 'Параметр',
    kernelModel: 'Тип ядра',
    phylogeneticFamily: 'Семейство ОС',
    licenseModel: 'Тип лицензии',
    wikipediaSitelinks: 'Интервики в Wikipedia',
    links: 'ссылок',
    targetCpuOverlap: 'Пересечение архитектур CPU',
    overlap: 'Пересечение',
    shared: 'Общих',
    sharedByBoth: 'Общие для обеих',
    only: 'Только',
  },
  uk: {
    filters: 'Фільтри',
    searchPlaceholder: 'Пошук...',
    all: 'Всі',
    overview: 'Огляд',
    systems: 'Систем',
    compare: 'Порівняти',
    kernel: 'Ядро',
    inception: 'Створення',
    developer: 'Розробник',
    license: 'Ліцензія',
    primaryAuthor: 'Головний автор',
    distributionTerms: 'Умови розповсюдження',
    targetArchitectures: 'Архітектури CPU',
    lineageRelationships: 'Еволюційні зв’язки',
    upstreamArchitecture: 'Попередники та основа',
    downstreamDerivatives: 'Прямі нащадки',
    rootArchitecture: 'Коренева архітектура',
    terminalDistribution: 'Кінцева гілка (без нащадків)',
    wikipediaDossier: 'Матеріали Вікіпедії',
    photoAlbum: 'Матеріали та медіа',
    syncing: 'Синхронізація',
    loadingMaterials: 'Завантаження матеріалів та медіа...',
    viewWikipedia: 'Відкрити статтю Вікіпедії',
    expandImage: 'Збільшити зображення',
    unavailableIn: 'Недоступно мовою',
    showingEnglish: 'відображено англійською',
    close: 'Закрити',
    zoomIn: 'Збільшити',
    zoomOut: 'Зменшити',
    resetZoom: 'Скинути масштаб',
    graphFilters: 'Фільтри графа',
    significanceThreshold: 'Поріг значущості',
    majorTier: 'Ключові (10+)',
    notableTier: 'Помітні (5+)',
    allTier: 'Всі (0+)',
    islandsSectors: 'Сектори та сімейства',
    reset: 'Скинути',
    timeline: 'Хронологія',
    systemComparison: 'Порівняння систем',
    comparatorSubtitle: 'Крос-системний архітектурний аналіз і філогенетичний родовід',
    closeComparator: 'Закрити порівняння',
    searchComparePlaceholder: 'Пошук ОС для порівняння...',
    quickComparisons: 'Швидке порівняння:',
    concurrentGen: 'Одне покоління',
    bothOriginatedIn: 'Обидві системи з’явилися в',
    predates: 'передує',
    by: 'на',
    years: 'років',
    year: 'рік',
    swapSystems: 'Поміняти системи місцями',
    locateInGraph: 'Показати на графі',
    phylogeneticKinship: 'Філогенетична спорідненість та шлях сходження',
    separation: 'Дистанція',
    steps: 'кроків',
    isDirectAncestorOf: 'є прямим предком',
    generationsDownLineage: 'поколінь за родоводом',
    lowestCommonAncestor: 'Найближчий спільний предок (LCA)',
    bothTraceLca: 'Обидві системи ведуть свою філогенетичну спадщину від цього вузла.',
    traceToLca: 'Шлях до LCA',
    independentLineages: 'Незалежні гілки. Прямих спільних предків у графі не зафіксовано.',
    architecturalSpecMatrix: 'Матриця архітектурних специфікацій',
    metric: 'Параметр',
    kernelModel: 'Тип ядра',
    phylogeneticFamily: 'Сімейство ОС',
    licenseModel: 'Тип ліцензії',
    wikipediaSitelinks: 'Інтервікі у Wikipedia',
    links: 'посилань',
    targetCpuOverlap: 'Перетин архітектур CPU',
    overlap: 'Перетин',
    shared: 'Спільних',
    sharedByBoth: 'Спільні для обох',
    only: 'Тільки',
  },
  de: {
    filters: 'Filter',
    searchPlaceholder: 'Suchen...',
    all: 'Alle',
    overview: 'Übersicht',
    systems: 'Systeme',
    compare: 'Vergleichen',
    kernel: 'Kernel',
    inception: 'Entstehung',
    developer: 'Entwickler',
    license: 'Lizenz',
    primaryAuthor: 'Hauptautor',
    distributionTerms: 'Vertriebsbedingungen',
    targetArchitectures: 'Zielarchitekturen',
    lineageRelationships: 'Abstammungslinien',
    upstreamArchitecture: 'Ursprungsarchitektur',
    downstreamDerivatives: 'Direkte Ableitungen',
    rootArchitecture: 'Wurzelarchitektur',
    terminalDistribution: 'Endzweig (keine Ableitungen)',
    wikipediaDossier: 'Wikipedia-Dossier',
    photoAlbum: 'Materialien & Medien',
    syncing: 'Synchronisieren',
    loadingMaterials: 'Laden von Materialien & Medien...',
    viewWikipedia: 'Wikipedia-Artikel ansehen',
    expandImage: 'Bild vergrößern',
    unavailableIn: 'Nicht verfügbar auf',
    showingEnglish: 'Englische Version wird angezeigt',
    close: 'Schließen',
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    resetZoom: 'Zurücksetzen',
    graphFilters: 'Graph-Filter',
    significanceThreshold: 'Bedeutungsschwelle',
    majorTier: 'Bedeutend (10+)',
    notableTier: 'Bemerkenswert (5+)',
    allTier: 'Alle (0+)',
    islandsSectors: 'Sektoren & Familien',
    reset: 'Zurücksetzen',
    timeline: 'Zeitachse',
    systemComparison: 'Systemvergleich',
    comparatorSubtitle: 'Architekturanalyse und Stammbaum',
    closeComparator: 'Vergleich schließen',
    searchComparePlaceholder: 'Betriebssystem zum Vergleichen suchen...',
    quickComparisons: 'Schnellvergleich:',
    concurrentGen: 'Gleiche Generation',
    bothOriginatedIn: 'Beide Systeme stammen aus',
    predates: 'geht voraus',
    by: 'um',
    years: 'Jahre',
    year: 'Jahr',
    swapSystems: 'Systeme vertauschen',
    locateInGraph: 'Im Graph anzeigen',
    phylogeneticKinship: 'Stammbaum-Verwandtschaft und Konvergenzpfad',
    separation: 'Abstand',
    steps: 'Schritte',
    isDirectAncestorOf: 'ist ein direkter Vorfahre von',
    generationsDownLineage: 'Generationen in der Linie',
    lowestCommonAncestor: 'Jüngster gemeinsamer Vorfahre (LCA)',
    bothTraceLca: 'Beide Systeme führen ihr Erbe auf diesen gemeinsamen Meilenstein zurück.',
    traceToLca: 'Pfad zu LCA',
    independentLineages: 'Unabhängige Linien. Kein direkter gemeinsamer Vorfahre verzeichnet.',
    architecturalSpecMatrix: 'Architektur-Spezifikationsmatrix',
    metric: 'Metrik',
    kernelModel: 'Kernel-Modell',
    phylogeneticFamily: 'OS-Familie',
    licenseModel: 'Lizenzmodell',
    wikipediaSitelinks: 'Wikipedia-Sitelinks',
    links: 'Links',
    targetCpuOverlap: 'CPU-Architekturüberschneidung',
    overlap: 'Überschneidung',
    shared: 'Gemeinsam',
    sharedByBoth: 'Von beiden unterstützt',
    only: 'Nur',
  },
  fr: {
    filters: 'Filtres',
    searchPlaceholder: 'Rechercher...',
    all: 'Tous',
    overview: 'Aperçu',
    systems: 'Systèmes',
    compare: 'Comparer',
    kernel: 'Noyau',
    inception: 'Création',
    developer: 'Développeur',
    license: 'Licence',
    primaryAuthor: 'Auteur principal',
    distributionTerms: 'Conditions de distribution',
    targetArchitectures: 'Architectures cibles',
    lineageRelationships: 'Relations de lignée',
    upstreamArchitecture: 'Architecture parente',
    downstreamDerivatives: 'Dérivés directs',
    rootArchitecture: 'Architecture racine',
    terminalDistribution: 'Branche finale (aucun dérivé)',
    wikipediaDossier: 'Dossier Wikipédia',
    photoAlbum: 'Médias et documents',
    syncing: 'Synchronisation',
    loadingMaterials: 'Chargement des médias et documents...',
    viewWikipedia: 'Voir l’article Wikipédia',
    expandImage: 'Agrandir l’image',
    unavailableIn: 'Indisponible en',
    showingEnglish: 'affichage en anglais',
    close: 'Fermer',
    zoomIn: 'Zoom avant',
    zoomOut: 'Zoom arrière',
    resetZoom: 'Réinitialiser',
    graphFilters: 'Filtres du graphe',
    significanceThreshold: 'Seuil d’importance',
    majorTier: 'Majeurs (10+)',
    notableTier: 'Notables (5+)',
    allTier: 'Tous (0+)',
    islandsSectors: 'Secteurs & Familles',
    reset: 'Réinitialiser',
    timeline: 'Chronologie',
    systemComparison: 'Comparaison des systèmes',
    comparatorSubtitle: 'Analyse architecturale et lignée phylogénétique',
    closeComparator: 'Fermer le comparateur',
    searchComparePlaceholder: 'Rechercher un système d’exploitation à comparer...',
    quickComparisons: 'Comparaisons rapides :',
    concurrentGen: 'Génération concurrente',
    bothOriginatedIn: 'Les deux systèmes sont apparus en',
    predates: 'précède',
    by: 'de',
    years: 'ans',
    year: 'an',
    swapSystems: 'Intervertir les systèmes',
    locateInGraph: 'Localiser dans le graphe',
    phylogeneticKinship: 'Parenté phylogénétique et voie de convergence',
    separation: 'Séparation',
    steps: 'étapes',
    isDirectAncestorOf: 'est un ancêtre direct de',
    generationsDownLineage: 'générations dans la lignée',
    lowestCommonAncestor: 'Plus proche ancêtre commun (LCA)',
    bothTraceLca: 'Les deux systèmes font remonter leur héritage phylogénétique à ce jalon.',
    traceToLca: 'Tracé vers le LCA',
    independentLineages: 'Lignées indépendantes. Aucun ancêtre phylogénétique commun enregistré.',
    architecturalSpecMatrix: 'Matrice des spécifications architecturales',
    metric: 'Métrique',
    kernelModel: 'Modèle de noyau',
    phylogeneticFamily: 'Famille d’OS',
    licenseModel: 'Modèle de licence',
    wikipediaSitelinks: 'Liens interlangues Wikipédia',
    links: 'liens',
    targetCpuOverlap: 'Chevauchement d’architectures CPU',
    overlap: 'Chevauchement',
    shared: 'Partagé',
    sharedByBoth: 'Partagé par les deux',
    only: 'Uniquement',
  },
  es: {
    filters: 'Filtros',
    searchPlaceholder: 'Buscar...',
    all: 'Todos',
    overview: 'Resumen',
    systems: 'Sistemas',
    compare: 'Comparar',
    kernel: 'Núcleo',
    inception: 'Creación',
    developer: 'Desarrollador',
    license: 'Licencia',
    primaryAuthor: 'Autor principal',
    distributionTerms: 'Condiciones de distribución',
    targetArchitectures: 'Arquitecturas objetivo',
    lineageRelationships: 'Relaciones de linaje',
    upstreamArchitecture: 'Arquitectura ascendente',
    downstreamDerivatives: 'Derivados directos',
    rootArchitecture: 'Arquitectura raíz',
    terminalDistribution: 'Rama terminal (sin derivados)',
    wikipediaDossier: 'Dossier de Wikipedia',
    photoAlbum: 'Materiales y multimedia',
    syncing: 'Sincronizando',
    loadingMaterials: 'Cargando materiales y multimedia...',
    viewWikipedia: 'Ver dossier de Wikipedia',
    expandImage: 'Ampliar imagen',
    unavailableIn: 'No disponible en',
    showingEnglish: 'mostrando en inglés',
    close: 'Cerrar',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    resetZoom: 'Restablecer',
    graphFilters: 'Filtros del grafo',
    significanceThreshold: 'Umbral de relevancia',
    majorTier: 'Principales (10+)',
    notableTier: 'Notables (5+)',
    allTier: 'Todos (0+)',
    islandsSectors: 'Sectores y familias',
    reset: 'Restablecer',
    timeline: 'Línea de tiempo',
    systemComparison: 'Comparación de sistemas',
    comparatorSubtitle: 'Análisis arquitectónico y linaje filogenético',
    closeComparator: 'Cerrar comparador',
    searchComparePlaceholder: 'Buscar un sistema operativo para comparar...',
    quickComparisons: 'Comparaciones rápidas:',
    concurrentGen: 'Generación concurrente',
    bothOriginatedIn: 'Ambos sistemas se originaron en',
    predates: 'es anterior a',
    by: 'por',
    years: 'años',
    year: 'año',
    swapSystems: 'Intercambiar sistemas',
    locateInGraph: 'Localizar en el gráfico',
    phylogeneticKinship: 'Parentesco filogenético y ruta de convergencia',
    separation: 'Separación',
    steps: 'pasos',
    isDirectAncestorOf: 'es un antepasado directo de',
    generationsDownLineage: 'generaciones en el linaje',
    lowestCommonAncestor: 'Último ancestro común (LCA)',
    bothTraceLca: 'Ambos sistemas remontan su herencia filogenética a este hito.',
    traceToLca: 'Ruta al LCA',
    independentLineages: 'Linajes independientes. No hay un ancestro común directo registrado.',
    architecturalSpecMatrix: 'Matriz de especificaciones arquitectónicas',
    metric: 'Métrica',
    kernelModel: 'Modelo de núcleo',
    phylogeneticFamily: 'Familia de SO',
    licenseModel: 'Modelo de licencia',
    wikipediaSitelinks: 'Enlaces de Wikipedia',
    links: 'enlaces',
    targetCpuOverlap: 'Solapamiento de arquitecturas CPU',
    overlap: 'Solapamiento',
    shared: 'Compartidas',
    sharedByBoth: 'Compartidas por ambos',
    only: 'Solo',
  },
  pt: {
    filters: 'Filtros',
    searchPlaceholder: 'Pesquisar...',
    all: 'Todos',
    overview: 'Visão Geral',
    systems: 'Sistemas',
    compare: 'Comparar',
    kernel: 'Núcleo',
    inception: 'Criação',
    developer: 'Desenvolvedor',
    license: 'Licença',
    primaryAuthor: 'Autor principal',
    distributionTerms: 'Termos de distribuição',
    targetArchitectures: 'Arquiteturas-alvo',
    lineageRelationships: 'Relações de linhagem',
    upstreamArchitecture: 'Arquitetura ascendente',
    downstreamDerivatives: 'Derivados diretos',
    rootArchitecture: 'Arquitetura raiz',
    terminalDistribution: 'Ramo terminal (sem derivados)',
    wikipediaDossier: 'Dossiê da Wikipédia',
    photoAlbum: 'Materiais e mídia',
    syncing: 'Sincronizando',
    loadingMaterials: 'Carregando materiais e mídia...',
    viewWikipedia: 'Ver dossiê da Wikipédia',
    expandImage: 'Ampliar imagem',
    unavailableIn: 'Indisponível em',
    showingEnglish: 'exibindo em inglês',
    close: 'Fechar',
    zoomIn: 'Aproximar',
    zoomOut: 'Afastar',
    resetZoom: 'Redefinir',
    graphFilters: 'Filtros do grafo',
    significanceThreshold: 'Limiar de relevância',
    majorTier: 'Principais (10+)',
    notableTier: 'Notáveis (5+)',
    allTier: 'Todos (0+)',
    islandsSectors: 'Setores e famílias',
    reset: 'Redefinir',
    timeline: 'Linha do tempo',
    systemComparison: 'Comparação de sistemas',
    comparatorSubtitle: 'Análise arquitetônica e linhagem filogenética',
    closeComparator: 'Fechar comparador',
    searchComparePlaceholder: 'Pesquisar um sistema operacional para comparar...',
    quickComparisons: 'Comparações rápidas:',
    concurrentGen: 'Geração concorrente',
    bothOriginatedIn: 'Ambos os sistemas se originaram em',
    predates: 'antecede',
    by: 'por',
    years: 'anos',
    year: 'ano',
    swapSystems: 'Trocar sistemas',
    locateInGraph: 'Localizar no gráfico',
    phylogeneticKinship: 'Parentesco filogenético e caminho de convergência',
    separation: 'Separação',
    steps: 'passos',
    isDirectAncestorOf: 'é um ancestral direto de',
    generationsDownLineage: 'gerações na linhagem',
    lowestCommonAncestor: 'Ancestral comum mais recente (LCA)',
    bothTraceLca: 'Ambos os sistemas remontam sua herança filogenética a este marco.',
    traceToLca: 'Trajeto até o LCA',
    independentLineages: 'Linhagens independentes. Nenhum ancestral comum direto registrado.',
    architecturalSpecMatrix: 'Matriz de especificações arquitetônicas',
    metric: 'Métrica',
    kernelModel: 'Modelo de kernel',
    phylogeneticFamily: 'Família de SO',
    licenseModel: 'Modelo de licença',
    wikipediaSitelinks: 'Links da Wikipédia',
    links: 'links',
    targetCpuOverlap: 'Sobreposição de arquiteturas de CPU',
    overlap: 'Sobreposição',
    shared: 'Compartilhadas',
    sharedByBoth: 'Compartilhadas por ambos',
    only: 'Apenas',
  },
  ar: {
    filters: 'مرشحات',
    searchPlaceholder: 'بحث...',
    all: 'الكل',
    overview: 'نظرة عامة',
    systems: 'أنظمة',
    compare: 'مقارنة',
    kernel: 'النواة',
    inception: 'البداية',
    developer: 'المطور',
    license: 'الترخيص',
    primaryAuthor: 'المؤلف الرئيسي',
    distributionTerms: 'شروط التوزيع',
    targetArchitectures: 'المعماريات المستهدفة',
    lineageRelationships: 'علاقات السلالة',
    upstreamArchitecture: 'المعمارية الأصلية',
    downstreamDerivatives: 'المشتقات المباشرة',
    rootArchitecture: 'معمارية أصلية / جذرية',
    terminalDistribution: 'توزيع نهائي (بدون مشتقات)',
    wikipediaDossier: 'ملف ويكيبيديا',
    photoAlbum: 'المواد والوسائط',
    syncing: 'مزامنة',
    loadingMaterials: 'جارٍ تحميل المواد والوسائط...',
    viewWikipedia: 'عرض ملف ويكيبيديا',
    expandImage: 'تكبير الصورة',
    unavailableIn: 'غير متوفر بلغة',
    showingEnglish: 'عرض باللغة الإنجليزية',
    close: 'إغلاق',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    resetZoom: 'إعادة ضبط',
    graphFilters: 'مرشحات الرسم',
    significanceThreshold: 'عتبة الأهمية',
    majorTier: 'رئيسي (10+)',
    notableTier: 'ملحوظ (5+)',
    allTier: 'الكل (0+)',
    islandsSectors: 'القطاعات والعائلات',
    reset: 'إعادة ضبط',
    timeline: 'الجدول الزمني',
    systemComparison: 'مقارنة الأنظمة',
    comparatorSubtitle: 'التحليل المعماري والنسب الفيلوجيني',
    closeComparator: 'إغلاق المقارنة',
    searchComparePlaceholder: 'ابحث عن نظام تشغيل للمقارنة...',
    quickComparisons: 'مقارنات سريعة:',
    concurrentGen: 'جيل متزامن',
    bothOriginatedIn: 'نشأ كلا النظامين في',
    predates: 'يسبق',
    by: 'بمقدار',
    years: 'سنوات',
    year: 'سنة',
    swapSystems: 'تبديل الأنظمة',
    locateInGraph: 'تحديد في الرسم البياني',
    phylogeneticKinship: 'القرابة الفيلوجينية ومسار التقارب',
    separation: 'المسافة',
    steps: 'خطوات',
    isDirectAncestorOf: 'هو سلف مباشر لـ',
    generationsDownLineage: 'أجيال في النسب',
    lowestCommonAncestor: 'أحدث سلف مشترك (LCA)',
    bothTraceLca: 'يتتبع كلا النظامين تراثهما الفيلوجيني إلى هذا المعلم.',
    traceToLca: 'المسار إلى LCA',
    independentLineages: 'سلالات مستقلة. لا يوجد سلف مشترك مسجل في الرسم.',
    architecturalSpecMatrix: 'مصفوفة المواصفات المعمارية',
    metric: 'المقياس',
    kernelModel: 'نموذج النواة',
    phylogeneticFamily: 'عائلة النظام',
    licenseModel: 'نموذج الترخيص',
    wikipediaSitelinks: 'روابط ويكيبيديا',
    links: 'روابط',
    targetCpuOverlap: 'تداخل معمارية وحدة المعالجة المركزية',
    overlap: 'تداخل',
    shared: 'مشترك',
    sharedByBoth: 'مشترك بين الاثنين',
    only: 'فقط',
  },
  ja: {
    filters: 'フィルター',
    searchPlaceholder: '検索...',
    all: 'すべて',
    overview: '概要',
    systems: 'システム',
    compare: '比較',
    kernel: 'カーネル',
    inception: '誕生年',
    developer: '開発者',
    license: 'ライセンス',
    primaryAuthor: '主著者',
    distributionTerms: '配布条件',
    targetArchitectures: '対象アーキテクチャ',
    lineageRelationships: '系譜関係',
    upstreamArchitecture: '上位アーキテクチャ',
    downstreamDerivatives: '直接の派生OS',
    rootArchitecture: 'ルートアーキテクチャ',
    terminalDistribution: '最終派生（派生なし）',
    wikipediaDossier: 'Wikipedia資料',
    photoAlbum: '資料・メディア',
    syncing: '同期中',
    loadingMaterials: '資料・メディアを読み込み中...',
    viewWikipedia: 'Wikipedia資料を開く',
    expandImage: '画像を拡大',
    unavailableIn: '未提供言語:',
    showingEnglish: '英語で表示中',
    close: '閉じる',
    zoomIn: '拡大',
    zoomOut: '縮小',
    resetZoom: '初期値に戻す',
    graphFilters: 'グラフフィルター',
    significanceThreshold: '重要度基準',
    majorTier: '主要 (10+)',
    notableTier: '注目 (5+)',
    allTier: 'すべて (0+)',
    islandsSectors: 'セクター＆ファミリー',
    reset: 'リセット',
    timeline: 'タイムライン',
    systemComparison: 'システム比較',
    comparatorSubtitle: 'システム間アーキテクチャ分析と系統樹',
    closeComparator: '比較を閉じる',
    searchComparePlaceholder: '比較するOSを検索...',
    quickComparisons: 'クイック比較:',
    concurrentGen: '同世代',
    bothOriginatedIn: '両システムとも次の年に誕生:',
    predates: 'より前の登場:',
    by: '差:',
    years: '年',
    year: '年',
    swapSystems: 'システムを入れ替える',
    locateInGraph: 'グラフで位置を表示',
    phylogeneticKinship: '系統的関係と収束経路',
    separation: '距離',
    steps: 'ステップ',
    isDirectAncestorOf: 'の直接の祖先です:',
    generationsDownLineage: '世代離れています',
    lowestCommonAncestor: '最も近い共通の祖先 (LCA)',
    bothTraceLca: '両システムとも系統のルーツをこのマイルストーンに辿ることができます。',
    traceToLca: 'LCAへの経路',
    independentLineages: '独立した系統です。共通の祖先は記録されていません。',
    architecturalSpecMatrix: 'アーキテクチャ仕様マトリックス',
    metric: '項目',
    kernelModel: 'カーネルモデル',
    phylogeneticFamily: '系統ファミリー',
    licenseModel: 'ライセンスモデル',
    wikipediaSitelinks: 'Wikipedia サイトリンク',
    links: '件',
    targetCpuOverlap: '対象CPUアーキテクチャの重複',
    overlap: '重複',
    shared: '共通',
    sharedByBoth: '両システムで共通',
    only: 'のみ:',
  },
  zh: {
    filters: '筛选器',
    searchPlaceholder: '搜索...',
    all: '全部',
    overview: '总览',
    systems: '个系统',
    compare: '对比',
    kernel: '内核',
    inception: '诞生年份',
    developer: '开发者',
    license: '软件许可',
    primaryAuthor: '主要作者',
    distributionTerms: '分发条款',
    targetArchitectures: '目标架构',
    lineageRelationships: '谱系关系',
    upstreamArchitecture: '上游架构',
    downstreamDerivatives: '下游衍生系统',
    rootArchitecture: '根系架构',
    terminalDistribution: '最终分支（无下游衍生）',
    wikipediaDossier: '维基百科档案',
    photoAlbum: '相关资料与媒体',
    syncing: '同步中',
    loadingMaterials: '正在加载资料与媒体...',
    viewWikipedia: '查看维基百科条目',
    expandImage: '查看原图',
    unavailableIn: '暂无该语言内容：',
    showingEnglish: '已显示英文原版',
    close: '关闭',
    zoomIn: '放大',
    zoomOut: '缩小',
    resetZoom: '重置缩放',
    graphFilters: '图谱筛选',
    significanceThreshold: '重要性阈值',
    majorTier: '核心 (10+)',
    notableTier: '知名 (5+)',
    allTier: '全部 (0+)',
    islandsSectors: '分支家族',
    reset: '重置',
    timeline: '时间线',
    systemComparison: '系统对比',
    comparatorSubtitle: '跨系统架构分析与系谱树',
    closeComparator: '关闭对比',
    searchComparePlaceholder: '搜索要对比的操作系统...',
    quickComparisons: '快速对比：',
    concurrentGen: '同代系统',
    bothOriginatedIn: '两个系统均诞生于',
    predates: '早于',
    by: '差',
    years: '年',
    year: '年',
    swapSystems: '交换系统',
    locateInGraph: '在图谱中定位',
    phylogeneticKinship: '系谱亲缘关系与聚合路径',
    separation: '距离',
    steps: '步',
    isDirectAncestorOf: '是的直接祖先',
    generationsDownLineage: '个世代',
    lowestCommonAncestor: '最近共同祖先 (LCA)',
    bothTraceLca: '两个系统的谱系根源均可追溯至此节点。',
    traceToLca: '追溯至 LCA',
    independentLineages: '独立谱系。在系统图谱中未记录到直接的共享祖先。',
    architecturalSpecMatrix: '架构规格矩阵',
    metric: '指标',
    kernelModel: '内核模型',
    phylogeneticFamily: '谱系家族',
    licenseModel: '许可证模型',
    wikipediaSitelinks: '维基百科词条链接',
    links: '条',
    targetCpuOverlap: '目标 CPU 架构重叠度',
    overlap: '重叠',
    shared: '共有',
    sharedByBoth: '两者共有',
    only: '仅',
  },
  hi: {
    filters: 'फ़िल्टर',
    searchPlaceholder: 'खोजें...',
    all: 'सभी',
    overview: 'अवलोकन',
    systems: 'सिस्टम',
    compare: 'तुलना करें',
    kernel: 'कर्नेल',
    inception: 'आरंभ वर्ष',
    developer: 'डेवलपर',
    license: 'लाइसेंस',
    primaryAuthor: 'मुख्य लेखक',
    distributionTerms: 'वितरण शर्तें',
    targetArchitectures: 'लक्षित आर्किटेक्चर',
    lineageRelationships: 'वंशावली संबंध',
    upstreamArchitecture: 'मूल आर्किटेक्चर',
    downstreamDerivatives: 'प्रत्यक्ष व्युत्पन्न',
    rootArchitecture: 'मूल / स्वतंत्र आर्किटेक्चर',
    terminalDistribution: 'अंतिम शाखा (कोई व्युत्पन्न नहीं)',
    wikipediaDossier: 'विकिपीडिया दस्तावेज़',
    photoAlbum: 'सामग्री और मीडिया',
    syncing: 'सिंक हो रहा है',
    loadingMaterials: 'सामग्री और मीडिया लोड हो रहा है...',
    viewWikipedia: 'विकिपीडिया लेख देखें',
    expandImage: 'छवि बड़ी करें',
    unavailableIn: 'भाषा में अनुपलब्ध:',
    showingEnglish: 'अंग्रेज़ी में प्रदर्शित',
    close: 'बंद करें',
    zoomIn: 'बड़ा करें',
    zoomOut: 'छोटा करें',
    resetZoom: 'रीसेट करें',
    graphFilters: 'ग्राफ़ फ़िल्टर',
    significanceThreshold: 'महत्व सीमा',
    majorTier: 'प्रमुख (10+)',
    notableTier: 'उल्लेखनीय (5+)',
    allTier: 'सभी (0+)',
    islandsSectors: 'क्षेत्र और परिवार',
    reset: 'रीसेट',
    timeline: 'समयरेखा',
    systemComparison: 'सिस्टम तुलना',
    comparatorSubtitle: 'क्रॉस-सिस्टम वास्तुकला विश्लेषण और वंशावली',
    closeComparator: 'तुलना बंद करें',
    searchComparePlaceholder: 'तुलना करने के लिए ऑपरेटिंग सिस्टम खोजें...',
    quickComparisons: 'त्वरित तुलना:',
    concurrentGen: 'समवर्ती पीढ़ी',
    bothOriginatedIn: 'दोनों सिस्टम की शुरुआत हुई थी',
    predates: 'से पहले का है',
    by: 'द्वारा',
    years: 'वर्ष',
    year: 'वर्ष',
    swapSystems: 'सिस्टम बदलें',
    locateInGraph: 'ग्राफ़ में खोजें',
    phylogeneticKinship: 'वंशावलीय संबंध और अभिसरण पथ',
    separation: 'अंतर',
    steps: 'चरण',
    isDirectAncestorOf: 'का प्रत्यक्ष पूर्वज है',
    generationsDownLineage: 'पीढ़ियां नीचे',
    lowestCommonAncestor: 'निकटतम सामान्य पूर्वज (LCA)',
    bothTraceLca: 'दोनों प्रणालियां अपनी वंशावली विरासत को इस मील के पत्थर तक जोड़ती हैं।',
    traceToLca: 'LCA का पथ',
    independentLineages: 'स्वतंत्र वंशावली। सिस्टम ग्राफ़ में कोई सीधा साझा पूर्वज दर्ज नहीं है।',
    architecturalSpecMatrix: 'वास्तुशिल्प विनिर्देश मैट्रिक्स',
    metric: 'पैमाना',
    kernelModel: 'कर्नेल मॉडल',
    phylogeneticFamily: 'वंशावली परिवार',
    licenseModel: 'लाइसेंस मॉडल',
    wikipediaSitelinks: 'विकिपीडिया साइटलिंक्स',
    links: 'लिंक्स',
    targetCpuOverlap: 'लक्षित सीपीयू आर्किटेक्चर ओवरलैप',
    overlap: 'ओवरलैप',
    shared: 'साझा',
    sharedByBoth: 'दोनों द्वारा साझा',
    only: 'केवल',
  },
};

export function t(key: TranslationKey, langCode = 'en'): string {
  const dict = TRANSLATIONS[langCode] || TRANSLATIONS.en;
  return dict[key] || TRANSLATIONS.en[key] || key;
}
